---
apiVersion: tekton.dev/v1alpha1
kind: PipelineResource
metadata:
  name: web-repo
spec:
  type: git
  params:
  - name: url
    value: https://github.com/Spider-Art/nginx-s2i.git
---
apiVersion: tekton.dev/v1alpha1
kind: PipelineResource
metadata:
  name: api-image
spec:
  type: image
  params:
  - name: url
    value: image-registry.openshift-image-registry.svc:5000/pipelines-tutorial/vote-api:latest
